name: Deploy

on:
  push:
    paths:
      - 'front-end/**'
    branches:
      - main
  pull_request:
    paths:
      - 'front-end/**'
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy
    needs:
      - build
      - lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: ${{ github.workspace }}/dist

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ github.workspace }}/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
